version: "3.9"

services:
  db:
    image: postgres:15
    container_name: Hero_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: Hero_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      HERO_OPENROUTER_API_KEY: ${HERO_OPENROUTER_API_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      NODE_ENV: production
    entrypoint: ["./wait-for-postgres.sh", "db", "npm", "run", "start"]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: Hero_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # frontend will now be visible on localhost:3000
    depends_on:
      - backend
    entrypoint: ["./wait-for-backend.sh"]

volumes:
  db_data:
